[build]
  command = "npm run build && npm run cypress:run"
  publish = ".next"

[build.cache]
  path = "/opt/build/repo/node_modules/.cache/CypressBinary/14.0.3/Cypress/Cypress"

[dev]
  command = "npm run start"