[build]
  command = "npm run build && npm run cypress:install && npm run cypress:run"
  publish = ".next"

[context.production.environment]
  NODE_ENV = "production"

[build.environment]
  CYPRESS_CACHE_FOLDER = "/opt/buildhome/.cache/Cypress"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["node_modules", "/opt/buildhome/.cache/Cypress"]
